apiVersion: apps/v1
kind: Deployment
metadata:
  name: institute-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: institute
  template:
    metadata:
      labels:
        app: institute
    spec:
      containers:
        - name: institute
          image: us.gcr.io/deducee-333504/institute
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY