apiVersion: apps/v1
kind: Deployment
metadata:
  name: notices-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notices
  template:
    metadata:
      labels:
        app: notices
    spec:
      containers:
        - name: notices
          image: us.gcr.io/deducee-333504/notices
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY